# name
name: hello, world

# trigger
on:
  push:
    branches:
      - main
  workflow_dispatch:

# one or more jobs
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Greet the world
        run: echo "Hello, world! $(date)"
      