name: build_countingbook_app

on: [push]

jobs:
  build:
    name: Build Countingbook App
    runs-on: ubuntu-latest

    steps:
    - id: s01
      run: echo "github ${{ github.ref}}"
    # Setup the environment
    - run: echo "before " && ls -l
    - id: s02
      uses: actions/setup-node@v4
      with:
        node-version: 24
    - id: s03
      uses: actions/checkout@v5
    - run: echo "after " && ls -l
    - id: s04
      # Install Angular CLI and dependencies from package.json
      run: npm i -g @angular/cli && npm ci && echo "Angular CLI and dependencies installed"
    - id: s05
      # Build the Angular application
      run: ng build --configuration production
    - id: s06
      run: ls -l dist/countingbook/browser/
    - id: s07
      uses: nwtgck/actions-netlify@v2.1
      with:
        publish-dir: 'dist/countingbook/browser'
        production-deploys: true
      env:
        # github-token: ${{ secrets.GITHUB_TOKEN }}
        netlify-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        site-id: ${{ secrets.NETLIFY_SITE_ID }}
        # alias: ${{ secrets.NETLIFY_ALIAS }}
        # alias: ${{ secrets.NETLIFY_ALIAS }}
